# Generated by Django 4.1.3 on 2022-12-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='length_of_product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_contact_person_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='manufacturer_contact_person_name',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='manufacturer_contact_person_phone_number',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='manufacturing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturingunit'),
        ),
    ]
