# Generated by Django 4.1.4 on 2023-10-24 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_inventory_purchase_order_alter_inventory_barcode_and_more'),
        ('task', '0002_remove_productdetail_length_of_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('terms_and_condition', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancel', 'Cancel')], default='Placed', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='addpurchaseorderproduct',
            name='manufacturing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturingunit'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='m_industry',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='manufacturingunit',
            name='manufacturers',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingunit',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='gst',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='price',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gst',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manufacturing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturingunit'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproductdetail',
            name='gst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproductdetail',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='gst',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_industry',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='addpurchaseorderproduct',
            name='vendor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.vendorunit'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='customer_order_approval',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Order Placed', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('Accepted', 'Accepted'), ('Accepted with change', 'Accepted with change'), ('In Production', 'In Production'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='order placed', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.vendorunit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproductdetail',
            name='customer_order_approval',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Order Placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderproductdetail',
            name='vendor_order_approval',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Accepted with change', 'Accepted with change'), ('Cancel', 'Cancel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('Accepted', 'Accepted'), ('Accepted with change', 'Accepted with change'), ('In Production', 'In Production'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='order placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_order',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='TempInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('tax', models.CharField(blank=True, max_length=200, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=200, null=True)),
                ('itemCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturer')),
                ('manufacturing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturingunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_of_product', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('new_product', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.quotation')),
                ('tempproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.tempinventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='assigning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.manufacturingunit'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
