# Generated by Django 4.1.4 on 2023-10-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_productdetail_length_of_product_and_more'),
        ('inventory', '0006_alter_warehouse_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rack'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_or_service',
            field=models.CharField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='racks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(blank=True, choices=[('Sell', 'Sell'), ('Buy', 'Buy'), ('Both', 'Both')], default='Sell', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('Kg', 'Kg'), ('M', 'M')], default='Kg', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
